# Generated by Django 4.1 on 2024-04-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("task", "0001_initial"),
        ("quantization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantization",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantizations",
                to="task.task",
            ),
        ),
    ]
