# Generated by Django 4.1 on 2024-04-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quantization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantization",
            name="method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
