# Generated by Django 4.1 on 2024-04-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Generation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "result_image_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "generation",
                "verbose_name_plural": "generations",
                "db_table": "generation",
            },
        ),
    ]
