# Generated by Django 4.1 on 2024-04-26 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_path", models.CharField(max_length=500)),
                ("pixel_count", models.IntegerField()),
                ("color_count", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("image_type", models.CharField(max_length=50)),
                ("image_size", models.FloatField()),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
                "db_table": "image",
            },
        ),
    ]
